spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e-commerce?createDatabaseIfNotExist=true
    username: yuri
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect