spring:
  datasource:
    url: "postgres://twegsirbywxyqn:00a9169144267573bad9ba6ad08ec9a7689
    ecd6f1cb51967de966f884414ea4b@ec2-3-220-207-90.compute-1.amazonaws.com:5432/dadf91jfrhjg1"
  jpa:
    hibernate:
      ddl-auto: none
    jpa:
      show-sql: false
      properties.hibernate.formatsql: false