spring:
  mail:
    host: "smtp.gmail.com"
    username: "${EMAIL_USERNAME:vazio}"
    password: "${EMAIL_PASSWORD:vazio}"
    properties.mail.smtp:
      auth: "true"
      socketFactory:
        port: "465"
        class: "javax.net.ssl.SSLSocketFactory"
        fallback: "false"
      starttls.enable: "true"
      ssl.enable: "true"

  datasource:
    url: "${DATABASE_URL:teste}"
  jpa:
    hibernate:
      ddl-auto: "none"
    jpa:
      show-sql: "false"
      properties.hibernate.formatsql: "false"