spring:
  datasource:
    url: "${database_url:jdbc:mysql://localhost:3306/e-commerce?createDatabaseIfNotExist=true}"
    username: "${database_username:yuri}"
    password: "${database_password:123456}"
  main.allow-circular-references: "true"
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: "update"
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
  mail:
    host: "smtp.gmail.com"
    username: "teste@gmail.com"
    password: "senhagerada"
#    Usando TLS, se fosse usar SSL seria com a porta 465
    port: 587
    properties.mail.smtp:
      auth: "true"
      starttls.enable: "true"
      starttls.required: "true"
      writetimeout: "5000"
      timeout: "5000"
      connectiontimeout: "5000"