spring:
  datasource:
    url: "${database_url:jdbc:mysql://localhost:3306/e-commerce?createDatabaseIfNotExist=true}"
    username: "${database_username:yuri}"
    password: "${database_password:123456}"
  main.allow-circular-references: "true"
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: "update"
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
  mail:
    host: "smtp.gmail.com"
    username: "${email_username:teste}"
    password: "${email_password:teste}"
    properties.mail.smtp:
      auth: "true"
      socketFactory:
        port: "465"
        class: "javax.net.ssl.SSLSocketFactory"
        fallback: "false"
      starttls.enable: "true"
      ssl.enable: "true"