spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/e-commerce?createDatabaseIfNotExist=true"
    username: "yuri"
    password: "123456"
  main.allow-circular-references: "true"
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: "update"
    database-platform: "org.hibernate.dialect.MySQL8Dialect"